apiVersion: apps/v1
kind: Deployment
metadata:
  name: concurrent-port-scanner
  labels:
    app: concurrent-port-scanner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: concurrent-port-scanner
  template:
    metadata:
      labels:
        app: concurrent-port-scanner
    spec:
      containers:
        - name: port-scanner
          image: sadikbs23/concurrent-port-scanner:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: port-scanner-service
spec:
  selector:
    app: concurrent-port-scanner
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003 # Optional: Specify a custom NodePort (range: 30000-32767)
  type: NodePort
